// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_System.Models
{
    public partial class Category
    {
        public Category()
        {
            InverseParent_Category = new HashSet<Category>();
            Products = new HashSet<Product>();
        }

        [Key]
        public int Id { get; set; }
        public int? Parent_Category_Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Description { get; set; }

        [ForeignKey("Parent_Category_Id")]
        [InverseProperty("InverseParent_Category")]
        public virtual Category Parent_Category { get; set; }
        [InverseProperty("Parent_Category")]
        public virtual ICollection<Category> InverseParent_Category { get; set; }
        [InverseProperty("Category")]
        public virtual ICollection<Product> Products { get; set; }
    }
}