// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_System.Models
{
    [Table("Products_Order")]
    public partial class Products_Order
    {
        [Key]
        public int Product_Id { get; set; }
        [Key]
        public int Order_Id { get; set; }
        public int Product_Quantity { get; set; }

        [ForeignKey("Order_Id")]
        [InverseProperty("Products_Orders")]
        public virtual Order Order { get; set; }
        [ForeignKey("Product_Id")]
        [InverseProperty("Products_Orders")]
        public virtual Product Product { get; set; }
    }
}