// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_System.Models
{
    public partial class Product
    {
        public Product()
        {
            Products_Orders = new HashSet<Products_Order>();
        }

        [Key]
        public int Id { get; set; }
        public int? Category_Id { get; set; }
        public int? Vendor_Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string En_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Ar_Name { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        [Unicode(false)]
        public string Description { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }

        [ForeignKey("Category_Id")]
        [InverseProperty("Products")]
        public virtual Category Category { get; set; }
        [ForeignKey("Vendor_Id")]
        [InverseProperty("Products")]
        public virtual Vendor Vendor { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<Products_Order> Products_Orders { get; set; }
    }
}