// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_System.Models
{
    [Index("Email", Name = "IX_Users_Email", IsUnique = true)]
    [Index("UserName", Name = "IX_Users_UserName", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            Carts = new HashSet<Cart>();
            Orders = new HashSet<Order>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string UserName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string Mobile { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Address { get; set; }
        public bool IsAdmin { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Cart> Carts { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}